### ISSUE TITLE
hí mấy bẹn

### ISSUE THREAD

**Issue by NguyenTheVinh4310A13** [NguyenTheVinh4310A13/Lop-10A13-Nhom-04#1]

**Comment by NguyenTheVinh4310A13** [comment]
ai làm câu 2 đi, tui làm câu 1 rồi đó

**Comment by KhanhLinh10a13** [comment]
=)))))))) mọi người làm bài ổn k

**Comment by HoaiNhi22026** [comment]
Khum ổn🤧🤧

**Comment by KhanhLinh10a13** [comment]
tôi cũng vậy đau lòng quớ TT

**Comment by HoaiNhi22026** [comment]
T làm câu 2 nha

**Comment by ThaoUyen10a13** [comment]
Ủa sao để cái tên ngộ z:)

**Comment by ThaoUyen10a13** [comment]
đổi tên issue đi zinh ới

**Comment by ThaoUyen10a13** [comment]
sao ko đặt tối nay ăn j:)?

**Comment by DoanTrang10A13PhuNhuan** [comment]
Mệt mỏi quá :(((

**Comment by KhanhLinh10a13** [comment]
@DoanTrang10A13PhuNhuan tôi cũng vậy

**Comment by ThaoUyen10a13** [comment]
t ms ăn mì cay mà trộn zới cơm xịt thêm mayonaise,nó chả ra cái thể thống j cạ!:((

**Comment by NguyenTheVinh4310A13** [comment]
tập trung làm bài đi mn :))

**Comment by DoanTrang10A13PhuNhuan** [comment]
Giờ ngồi làm hoá sử nữa :(((((

**Comment by HoaiNhi22026** [comment]
Làm bài nào v

**Comment by KhanhLinh10a13** [comment]
@NguyenTheVinh4310A13 làm ỗn hong

**Comment by ThaoUyen10a13** [comment]
copy link nộp đi zinh ới

**Comment by NguyenTheVinh4310A13** [comment]
oke

**Comment by NguyenTheVinh4310A13** [comment]
làm s để nộp v
